export const kits = [
  {
    slug: "smart-city-glass-control-v2",
    layout: "glass",
    title: "Glass Control",
    eyebrow: "Smart City / Glass Control",
    domain: "Citizen operations",
    style: "Glassmorphism",
    summary: "Dark civic control room language with frosted telemetry, fast command access, and confidence-first hierarchy.",
    theme: {
      canvas: "#06121f",
      panel: "rgba(10, 30, 49, 0.72)",
      panelStrong: "rgba(16, 41, 67, 0.9)",
      ink: "#eaf7ff",
      mute: "#8eabc7",
      line: "rgba(139, 221, 255, 0.22)",
      primary: "#5ee4ff",
      primaryInk: "#021218",
      secondary: "#17324e",
      accent: "#8b7dff",
      success: "#45d9a6",
      warning: "#ffb454",
      shadow: "0 28px 90px rgba(0, 8, 20, 0.48)",
      radius: "28px",
      backgroundArt: "radial-gradient(circle at top right, rgba(94,228,255,0.18), transparent 28%), linear-gradient(180deg, #071221 0%, #081525 42%, #06101b 100%)",
    },
    nav: ["Ops map", "Transit", "Utilities", "Safety", "Access"],
    breadcrumbs: ["Kits", "Smart City", "Glass Control"],
    tabs: ["Overview", "States", "Accessibility"],
    toggles: ["Live", "Queued", "Escalated"],
    palette: [["Primary", "#5ee4ff"], ["Accent", "#8b7dff"], ["Success", "#45d9a6"], ["Warning", "#ffb454"], ["Surface", "#102943"]],
    metrics: [["Riders synced", "118k", "+12%", "primary"], ["Grid uptime", "99.98%", "+0.2%", "success"], ["Response time", "6m 24s", "-18%", "accent"], ["Air index", "42 AQI", "Stable", "warning"]],
    bars: [["Transit", 82, "primary"], ["Energy", 74, "accent"], ["Water", 66, "success"], ["Safety", 54, "warning"]],
    table: [["Blue line kiosks", "Synced", "94% adoption", "Mobility"], ["Flood lane sensors", "Ready", "4m ETA", "Safety"], ["Street mesh", "Monitoring", "1,240 nodes", "Digital"], ["Grid backup", "Balanced", "31 zones", "Utilities"]],
    composition: [["Control deck", "Fast", "Dense surfaces keep alerts and commands visible."], ["Telemetry cards", "Crisp", "Numbers dominate first glance."], ["Service shell", "Confident", "Glass chrome stays functional."]],
    commands: ["Open outage sheet", "Inspect accessibility state", "Jump to transit table", "Review incident card"],
    form: { titleLabel: "Service card title", titlePlaceholder: "North district outage summary", noteLabel: "Operator note", notePlaceholder: "Summarize the public impact and next action...", selectLabel: "Response mode", selectOptions: ["Rapid", "Measured", "Briefing"], validationMessage: "Use at least five characters so operators can scan it quickly." },
    alert: { title: "Transit surge absorbed", body: "Fallback signage and rider notifications were pushed before queues crossed the threshold." },
    empty: { title: "No pinned modules", body: "Save the highest-signal controls here so desk teams can reopen them instantly.", cta: "Pin a control" },
  },
  {
    slug: "smart-city-stone-signal-v2",
    layout: "stone",
    title: "Stone Signal",
    eyebrow: "Smart City / Stone Signal",
    domain: "Public infrastructure",
    style: "Neumorphism",
    summary: "Restrained tactile infrastructure kit using mineral depth, soft relief, and grounded operational forms.",
    theme: {
      canvas: "#d8ddd9",
      panel: "#dde3de",
      panelStrong: "#e4e9e5",
      ink: "#1b2828",
      mute: "#5e6d6b",
      line: "rgba(27, 40, 40, 0.12)",
      primary: "#2f766e",
      primaryInk: "#f1faf8",
      secondary: "#cfd8d3",
      accent: "#4b5f7a",
      success: "#2d8a57",
      warning: "#b06c2d",
      shadow: "12px 12px 24px rgba(149, 158, 152, 0.48), -10px -10px 18px rgba(245, 248, 245, 0.82)",
      radius: "26px",
      backgroundArt: "linear-gradient(180deg, #e4e8e3 0%, #d5dbd6 100%)",
    },
    nav: ["Signals", "Maintenance", "Street assets", "Permits", "Notes"],
    breadcrumbs: ["Kits", "Smart City", "Stone Signal"],
    tabs: ["Relief", "Forms", "Status"],
    toggles: ["Citizen", "Field", "Back office"],
    palette: [["Primary", "#2f766e"], ["Accent", "#4b5f7a"], ["Success", "#2d8a57"], ["Warning", "#b06c2d"], ["Surface", "#dde3de"]],
    metrics: [["Street assets", "8,420", "+3%", "primary"], ["Crews ready", "19", "Stable", "accent"], ["Issue closure", "87%", "+6%", "success"], ["Permit wait", "3.2d", "-0.8d", "warning"]],
    bars: [["Lighting", 76, "primary"], ["Roadworks", 58, "accent"], ["Water", 72, "success"], ["Inspections", 43, "warning"]],
    table: [["Signal timing", "Published", "14 corridors", "Mobility"], ["Lamp inventory", "Audited", "8,420 poles", "Infrastructure"], ["Permit desk", "Ready", "4-step review", "Planning"], ["Drainage crews", "Scheduled", "12 zones", "Utilities"]],
    composition: [["Inset actions", "Tactile", "Relief is used only where click targets benefit from depth."], ["Signal rail", "Grounded", "The left rail behaves like an equipment bay."], ["Form stack", "Calm", "Field groups stay readable inside softer surfaces."]],
    commands: ["Inspect permit form", "Open tactile controls", "Compare status blocks", "Review street asset table"],
    form: { titleLabel: "Inspection bundle", titlePlaceholder: "North bridge safety check", noteLabel: "Field note", notePlaceholder: "Describe the issue in operational language...", selectLabel: "Surface mode", selectOptions: ["Accessible", "Balanced", "Dense"], validationMessage: "A clearer label keeps the tactile interface readable in the field." },
    alert: { title: "Drainage route updated", body: "Crews received the new service path after overnight rain watch thresholds changed." },
    empty: { title: "No tactile presets saved", body: "Store your most-used relief patterns here for quick operator access.", cta: "Save preset" },
  },
  {
    slug: "smart-city-district-bento-v2",
    layout: "bento",
    title: "District Bento",
    eyebrow: "Smart City / District Bento",
    domain: "Neighborhood services",
    style: "Bento grid",
    summary: "Warm modular civic system for district services, requests, amenities, and neighborhood programming.",
    theme: {
      canvas: "#f7f1e8",
      panel: "rgba(255, 251, 246, 0.88)",
      panelStrong: "#fffaf3",
      ink: "#2a2119",
      mute: "#746152",
      line: "rgba(42, 33, 25, 0.10)",
      primary: "#c6703d",
      primaryInk: "#fff9f4",
      secondary: "#eddcc9",
      accent: "#326f6b",
      success: "#518355",
      warning: "#a36b24",
      shadow: "0 24px 60px rgba(114, 88, 51, 0.14)",
      radius: "30px",
      backgroundArt: "radial-gradient(circle at top left, rgba(198,112,61,0.14), transparent 24%), linear-gradient(180deg, #fbf6ee 0%, #f3ebdf 100%)",
    },
    nav: ["Districts", "Events", "Transit", "Requests", "Facilities"],
    breadcrumbs: ["Kits", "Smart City", "District Bento"],
    tabs: ["Modules", "Families", "Rewards"],
    toggles: ["Nearby", "Planned", "Saved"],
    palette: [["Primary", "#c6703d"], ["Accent", "#326f6b"], ["Success", "#518355"], ["Warning", "#a36b24"], ["Surface", "#fffaf3"]],
    metrics: [["District cards", "42", "+7", "primary"], ["Requests closed", "91%", "+4%", "success"], ["Upcoming events", "214", "+31", "accent"], ["Amenity load", "73%", "Stable", "warning"]],
    bars: [["Parks", 78, "accent"], ["Transit", 66, "primary"], ["Waste", 58, "success"], ["Support", 41, "warning"]],
    table: [["Playground updates", "Queued", "18 districts", "Parks"], ["Library passport", "Live", "41 branches", "Culture"], ["Bus card top-up", "Expanding", "12 kiosks", "Transit"], ["Market permits", "Reviewing", "97% success", "District office"]],
    composition: [["Bento logic", "Layered", "Priority modules grow while secondary ones stay compact."], ["Neighborhood shell", "Friendly", "Community cards stay welcoming without losing rigor."], ["Request stack", "Clear", "Service actions live beside public-facing context."]],
    commands: ["Open event block", "Inspect request tile", "Review district overview", "Jump to amenities data"],
    form: { titleLabel: "Neighborhood module", titlePlaceholder: "Play street activation board", noteLabel: "Community note", notePlaceholder: "Write the message residents should see first...", selectLabel: "Module emphasis", selectOptions: ["Primary", "Support", "Compact"], validationMessage: "Give the module a clear label before placing it in the bento layout." },
    alert: { title: "Family events refreshed", body: "Weekend programming for four districts has been rebalanced around transit demand." },
    empty: { title: "No featured modules", body: "Promote the district surfaces you want residents to discover first.", cta: "Feature a module" },
  },
  {
    slug: "smart-city-civic-current-v2",
    layout: "current",
    title: "Civic Current",
    eyebrow: "Smart City / Civic Current",
    domain: "Utility and transit accounts",
    style: "Modern",
    summary: "Crisp operational product system for public-service accounts, billing, transit access, and service status.",
    theme: {
      canvas: "#eef4fb",
      panel: "rgba(255, 255, 255, 0.92)",
      panelStrong: "#ffffff",
      ink: "#152132",
      mute: "#617286",
      line: "rgba(21, 33, 50, 0.10)",
      primary: "#2563eb",
      primaryInk: "#eff6ff",
      secondary: "#dbeafe",
      accent: "#0f172a",
      success: "#198754",
      warning: "#d97706",
      shadow: "0 20px 60px rgba(37, 99, 235, 0.10)",
      radius: "24px",
      backgroundArt: "linear-gradient(180deg, #f7faff 0%, #eaf1f8 100%)",
    },
    nav: ["Accounts", "Billing", "Status", "Support", "Policies"],
    breadcrumbs: ["Kits", "Smart City", "Civic Current"],
    tabs: ["Core", "Operational", "Release notes"],
    toggles: ["Default", "Compact", "Guided"],
    palette: [["Primary", "#2563eb"], ["Accent", "#0f172a"], ["Success", "#198754"], ["Warning", "#d97706"], ["Surface", "#ffffff"]],
    metrics: [["Accounts", "132k", "+10%", "primary"], ["Resolution", "87%", "+6%", "success"], ["Wallet usage", "64%", "+14%", "accent"], ["Incidents", "12", "-4", "warning"]],
    bars: [["Accounts", 80, "primary"], ["Billing", 62, "accent"], ["Support", 57, "success"], ["Alerts", 35, "warning"]],
    table: [["Unified wallet", "Stable", "3 payment rails", "Finance"], ["Transit account", "Released", "54 stations", "Mobility"], ["Service inbox", "Optimized", "1.2s load", "Support"], ["Push digest", "Queued", "240k recipients", "Comms"]],
    composition: [["Core dashboard", "Versatile", "A straightforward grid balances operational and resident-facing needs."], ["Guided forms", "Practical", "Validation is visible without shouting."], ["Status shell", "Reliable", "Release notes and incidents share one system language."]],
    commands: ["Inspect wallet card", "Open release notes", "Review support states", "Jump to billing table"],
    form: { titleLabel: "Release note title", titlePlaceholder: "District billing card refresh", noteLabel: "Operational summary", notePlaceholder: "Describe the rollout, impact, and follow-up...", selectLabel: "Shipping pace", selectOptions: ["Steady", "Fast", "Monitored"], validationMessage: "Release note titles should be short enough to scan in an incident feed." },
    alert: { title: "Weekly status digest sent", body: "Subscribers received a service summary without failed billing notification batches." },
    empty: { title: "No release highlights", body: "Pin the product changes you want account managers and citizens to notice first.", cta: "Pin highlight" },
  },
  {
    slug: "smart-city-quiet-bureau-v2",
    layout: "bureau",
    title: "Quiet Bureau",
    eyebrow: "Smart City / Quiet Bureau",
    domain: "Public service forms",
    style: "Minimalism",
    summary: "Editorial public-service language built around paper tones, plain language, and formal spacing.",
    theme: {
      canvas: "#f5f0e7",
      panel: "rgba(255, 252, 248, 0.88)",
      panelStrong: "#fffaf5",
      ink: "#201910",
      mute: "#6f6152",
      line: "rgba(32, 25, 16, 0.10)",
      primary: "#245f57",
      primaryInk: "#eefbf7",
      secondary: "#e4ddd1",
      accent: "#8d5e3f",
      success: "#427a50",
      warning: "#a16a36",
      shadow: "0 18px 46px rgba(67, 47, 24, 0.10)",
      radius: "22px",
      backgroundArt: "linear-gradient(180deg, #f8f5ee 0%, #f1eadf 100%)",
    },
    nav: ["Guidance", "Forms", "Approvals", "Notices", "Archive"],
    breadcrumbs: ["Kits", "Smart City", "Quiet Bureau"],
    tabs: ["Forms", "Language", "Policy"],
    toggles: ["Readable", "Balanced", "Dense"],
    palette: [["Primary", "#245f57"], ["Accent", "#8d5e3f"], ["Success", "#427a50"], ["Warning", "#a16a36"], ["Surface", "#fffaf5"]],
    metrics: [["Completed forms", "86%", "+7%", "success"], ["Average wait", "3m 12s", "-22%", "primary"], ["Draft returns", "71%", "+4%", "accent"], ["Queue size", "148", "Stable", "warning"]],
    bars: [["Permits", 72, "primary"], ["Payments", 64, "success"], ["Reports", 48, "accent"], ["Support", 36, "warning"]],
    table: [["Residential permits", "Published", "4-step flow", "Planning"], ["Waste pickup", "Ready", "18 neighborhoods", "Sanitation"], ["Bus card renewal", "Piloting", "12 kiosks", "Transit"], ["Event booking", "Approved", "97% success", "Culture"]],
    composition: [["Policy stack", "Composed", "Formal spacing creates confidence before ornament enters the frame."], ["Form shelf", "Plainspoken", "Inputs and instructions prioritize readability."], ["Archive module", "Trustworthy", "Historical material fits the same quiet system."]],
    commands: ["Review policy card", "Inspect form copy", "Open archive entry", "Check contrast notes"],
    form: { titleLabel: "Resident request category", titlePlaceholder: "Parking permit renewal", noteLabel: "Confirmation copy", notePlaceholder: "Explain the next step in plain language...", selectLabel: "Tone choice", selectOptions: ["Formal", "Neutral", "Warm"], validationMessage: "The form label should make sense even when read without supporting context." },
    alert: { title: "Draft saved for return", body: "Residents can resume the form later without losing uploaded files or identity documents." },
    empty: { title: "No form shortcuts", body: "Surface the services that should be easiest to access during peak public demand.", cta: "Add a shortcut" },
  },
  {
    slug: "urban-mobility-studio-v2",
    layout: "mobility",
    title: "Mobility Studio",
    eyebrow: "Urban-adjacent / Mobility Studio",
    domain: "Urban mobility platform",
    style: "Editorial mobility",
    summary: "Kinetic editorial transport system with route urgency, wayfinding energy, and hard-contrast control surfaces.",
    theme: {
      canvas: "#0e131a",
      panel: "rgba(24, 32, 44, 0.92)",
      panelStrong: "#212c39",
      ink: "#f8fbff",
      mute: "#98a7ba",
      line: "rgba(248, 113, 113, 0.20)",
      primary: "#fb7185",
      primaryInk: "#2c0811",
      secondary: "#263344",
      accent: "#38bdf8",
      success: "#22c55e",
      warning: "#f59e0b",
      shadow: "0 30px 90px rgba(0, 0, 0, 0.45)",
      radius: "20px",
      backgroundArt: "radial-gradient(circle at top left, rgba(251,113,133,0.16), transparent 20%), linear-gradient(180deg, #0c1117 0%, #121923 100%)",
    },
    nav: ["Lines", "Stations", "Fleet", "Dispatch", "Tickets"],
    breadcrumbs: ["Kits", "Urban-adjacent", "Mobility Studio"],
    tabs: ["Editorial", "Fleet", "Rider"],
    toggles: ["Peak", "Metro", "Bus"],
    palette: [["Primary", "#fb7185"], ["Accent", "#38bdf8"], ["Success", "#22c55e"], ["Warning", "#f59e0b"], ["Surface", "#212c39"]],
    metrics: [["Trips", "1.2M", "+8%", "primary"], ["On-time rate", "93%", "+4%", "success"], ["Stations live", "142", "+12", "accent"], ["Incidents", "7", "-3", "warning"]],
    bars: [["Metro", 86, "primary"], ["Bus", 73, "accent"], ["Bike", 57, "success"], ["Support", 39, "warning"]],
    table: [["Wayfinding screens", "Live", "142 stations", "Passenger"], ["Ticket wallet", "Rolling", "4 modes", "Payments"], ["Headway panel", "Fast", "900ms refresh", "Ops"], ["Platform alerts", "Queued", "28 routes", "Control"]],
    composition: [["Route strip", "Directional", "Hero modules feel like transit signage rather than software chrome."], ["Dispatch cards", "Urgent", "Critical actions cut through immediately."], ["Rider shell", "Confident", "The same language works for consumer and ops surfaces."]],
    commands: ["Inspect route strip", "Open dispatch card", "Review ticket form", "Jump to fleet table"],
    form: { titleLabel: "Route module", titlePlaceholder: "Midtown express alert card", noteLabel: "Dispatch note", notePlaceholder: "Explain the rider impact and mitigation...", selectLabel: "Primary mode", selectOptions: ["Metro", "Bus", "Multimodal"], validationMessage: "Route modules need short, scannable language for platform displays." },
    alert: { title: "Express route added", body: "A commuter service has been published and the dispatch board reflects new headways." },
    empty: { title: "No saved route modules", body: "Pin the boards your operators reopen during every peak period.", cta: "Save route module" },
  },
  {
    slug: "urban-climate-orbit-v2",
    layout: "orbit",
    title: "Climate Orbit",
    eyebrow: "Urban-adjacent / Climate Orbit",
    domain: "Climate resilience platform",
    style: "Scientific eco-tech",
    summary: "Science-forward resilience system that frames climate data as calm, analytical decision support.",
    theme: {
      canvas: "#071713",
      panel: "rgba(11, 35, 29, 0.84)",
      panelStrong: "#12372f",
      ink: "#e8fff7",
      mute: "#8ab4ab",
      line: "rgba(94, 234, 212, 0.20)",
      primary: "#5eead4",
      primaryInk: "#03231b",
      secondary: "#173c35",
      accent: "#a3e635",
      success: "#4ade80",
      warning: "#facc15",
      shadow: "0 28px 90px rgba(1, 11, 8, 0.46)",
      radius: "28px",
      backgroundArt: "radial-gradient(circle at center, rgba(94,234,212,0.12), transparent 28%), linear-gradient(180deg, #081512 0%, #0b1f1a 100%)",
    },
    nav: ["Signals", "Forecasts", "Policy", "Suppliers", "Reporting"],
    breadcrumbs: ["Kits", "Urban-adjacent", "Climate Orbit"],
    tabs: ["Signals", "Forecast", "Reporting"],
    toggles: ["Net zero", "Water", "Coastal"],
    palette: [["Primary", "#5eead4"], ["Accent", "#a3e635"], ["Success", "#4ade80"], ["Warning", "#facc15"], ["Surface", "#12372f"]],
    metrics: [["Carbon tracked", "18.2Mt", "+14%", "primary"], ["Sites covered", "420", "+33", "accent"], ["Projects funded", "58", "+9", "success"], ["Risk alerts", "12", "-5", "warning"]],
    bars: [["Energy", 84, "primary"], ["Water", 68, "accent"], ["Waste", 61, "success"], ["Travel", 46, "warning"]],
    table: [["Supplier scorecards", "Updated", "94 vendors", "Procurement"], ["Flood adaptation", "Modeling", "12 assets", "Resilience"], ["Carbon projects", "On track", "58 projects", "Sustainability"], ["Water alerts", "Streaming", "19 basins", "Ops"]],
    composition: [["Orbital framing", "Calm", "Circular cues imply systems thinking without overpowering the data."], ["Scenario report", "Analytical", "Long-form reading and controls coexist cleanly."], ["Policy deck", "Measured", "Calls to action stay serious and non-performative."]],
    commands: ["Inspect forecast card", "Review supplier scorecard", "Open scenario dialog", "Jump to risk table"],
    form: { titleLabel: "Scenario title", titlePlaceholder: "Urban heat mitigation plan", noteLabel: "Analyst note", notePlaceholder: "Summarize the drivers, assumptions, and likely impact...", selectLabel: "Reporting cadence", selectOptions: ["Quarterly", "Monthly", "Event-driven"], validationMessage: "Scenario titles should identify the decision context, not just the hazard." },
    alert: { title: "Rainfall assumptions refreshed", body: "The latest resilience model is ready for policy review with updated basin weighting." },
    empty: { title: "No saved scenarios", body: "Store the resilience models your team revisits before city or board briefings.", cta: "Save scenario" },
  },
  {
    slug: "urban-grid-forge-v2",
    layout: "forge",
    title: "Grid Forge",
    eyebrow: "Urban-adjacent / Grid Forge",
    domain: "Energy orchestration",
    style: "Industrial premium",
    summary: "Forged-energy control system with disciplined alarm language and serious operational density.",
    theme: {
      canvas: "#120d09",
      panel: "rgba(32, 24, 18, 0.92)",
      panelStrong: "#2a2118",
      ink: "#fff7ed",
      mute: "#b6a292",
      line: "rgba(245, 158, 11, 0.18)",
      primary: "#f59e0b",
      primaryInk: "#2f1905",
      secondary: "#3b2d1d",
      accent: "#fb7185",
      success: "#34d399",
      warning: "#facc15",
      shadow: "0 34px 100px rgba(0, 0, 0, 0.50)",
      radius: "18px",
      backgroundArt: "linear-gradient(180deg, #130e0a 0%, #17110d 100%)",
    },
    nav: ["Console", "Assets", "Field ops", "Runbooks", "Events"],
    breadcrumbs: ["Kits", "Urban-adjacent", "Grid Forge"],
    tabs: ["Console", "Field", "Emergency"],
    toggles: ["High load", "Battery", "Weather"],
    palette: [["Primary", "#f59e0b"], ["Accent", "#fb7185"], ["Success", "#34d399"], ["Warning", "#facc15"], ["Surface", "#2a2118"]],
    metrics: [["Assets", "8,420", "+6%", "primary"], ["Dispatch accuracy", "96.4%", "+1.1%", "success"], ["Peak variance", "2.1%", "-0.7%", "accent"], ["Critical alarms", "3", "-2", "warning"]],
    bars: [["Load", 88, "primary"], ["Battery", 63, "accent"], ["Solar", 59, "success"], ["Incidents", 22, "warning"]],
    table: [["Substation board", "Stable", "14 live zones", "Grid ops"], ["Battery reserve", "Charging", "72% capacity", "Storage"], ["Field dispatch", "Ready", "19 crews", "Operations"], ["Storm automation", "Armed", "12 triggers", "Response"]],
    composition: [["Control deck", "Serious", "The main shell reads like equipment, not consumer software."], ["Alarm lane", "Restrained", "Warning color appears only when it needs to carry weight."], ["Runbook panel", "Operational", "The form system is optimized for shift handover clarity."]],
    commands: ["Inspect substation board", "Open emergency sheet", "Review crew route form", "Jump to alarm table"],
    form: { titleLabel: "Runbook title", titlePlaceholder: "Storm reserve switching", noteLabel: "Operator note", notePlaceholder: "Capture the rationale, constraints, and field risk...", selectLabel: "Response mode", selectOptions: ["Prepared", "Active", "Escalated"], validationMessage: "Runbook titles should identify the exact event and operating context." },
    alert: { title: "Peak event absorbed", body: "Storage automation offset the surge before any public load shedding was required." },
    empty: { title: "No emergency presets", body: "Save the response modules operators reach for under severe weather conditions.", cta: "Save preset" },
  },
  {
    slug: "urban-care-mesh-v2",
    layout: "care",
    title: "Care Mesh",
    eyebrow: "Urban-adjacent / Care Mesh",
    domain: "Digital care coordination",
    style: "Humane clinical",
    summary: "Humane clinical system with calmer urgency cues, explicit form guidance, and warm care-team surfaces.",
    theme: {
      canvas: "#eef7fb",
      panel: "rgba(255, 255, 255, 0.94)",
      panelStrong: "#ffffff",
      ink: "#173047",
      mute: "#688198",
      line: "rgba(14, 165, 233, 0.14)",
      primary: "#0ea5e9",
      primaryInk: "#effbff",
      secondary: "#d7f0ff",
      accent: "#14b8a6",
      success: "#16a34a",
      warning: "#eab308",
      shadow: "0 22px 60px rgba(14, 165, 233, 0.10)",
      radius: "30px",
      backgroundArt: "radial-gradient(circle at top left, rgba(14,165,233,0.10), transparent 18%), linear-gradient(180deg, #f5fbff 0%, #edf6fb 100%)",
    },
    nav: ["Patients", "Scheduling", "Messages", "Escalations", "Monitoring"],
    breadcrumbs: ["Kits", "Urban-adjacent", "Care Mesh"],
    tabs: ["Care flow", "Patient states", "Monitoring"],
    toggles: ["Urgent", "Follow-up", "Remote"],
    palette: [["Primary", "#0ea5e9"], ["Accent", "#14b8a6"], ["Success", "#16a34a"], ["Warning", "#eab308"], ["Surface", "#ffffff"]],
    metrics: [["Patients", "48k", "+12%", "primary"], ["Appointments", "93%", "+3%", "success"], ["Escalations", "284", "+18", "accent"], ["Remote alerts", "16", "-6", "warning"]],
    bars: [["Visits", 79, "primary"], ["Messages", 67, "accent"], ["Adherence", 62, "success"], ["Alerts", 28, "warning"]],
    table: [["Appointment board", "Stable", "42 clinics", "Scheduling"], ["Medication inbox", "Synced", "18 plans", "Pharmacy"], ["Remote check-ins", "Growing", "9 devices", "Monitoring"], ["Escalation queue", "Priority", "16 cases", "Nursing"]],
    composition: [["Care shell", "Warm", "The system uses softness to reduce stress without losing precision."], ["Guided forms", "Supportive", "Descriptions and validation stay close to the user’s next action."], ["Team feed", "Measured", "Urgency is visible without letting red dominate the interface."]],
    commands: ["Review care plan", "Inspect patient states", "Open escalation sheet", "Jump to monitoring table"],
    form: { titleLabel: "Care plan title", titlePlaceholder: "Post-discharge follow-up", noteLabel: "Clinician note", notePlaceholder: "Summarize the context and next clinical action...", selectLabel: "Care priority", selectOptions: ["Routine", "Follow-up", "High touch"], validationMessage: "Care plans should be labeled so any team member can understand the intent immediately." },
    alert: { title: "Monitoring alert resolved", body: "The patient baseline returned to normal and the escalation queue has been updated." },
    empty: { title: "No care shortcuts", body: "Pin the workflows staff need during discharge, escalation, or medication review.", cta: "Pin workflow" },
  },
  {
    slug: "urban-campus-wave-v2",
    layout: "campus",
    title: "Campus Wave",
    eyebrow: "Urban-adjacent / Campus Wave",
    domain: "Public education platform",
    style: "Contemporary campus",
    summary: "Contemporary education system with collaborative modules, optimistic framing, and practical academic tools.",
    theme: {
      canvas: "#fffdf6",
      panel: "rgba(255, 255, 255, 0.95)",
      panelStrong: "#ffffff",
      ink: "#1f2937",
      mute: "#6b7280",
      line: "rgba(249, 115, 22, 0.16)",
      primary: "#f97316",
      primaryInk: "#fff7ed",
      secondary: "#ffedd5",
      accent: "#0f766e",
      success: "#16a34a",
      warning: "#ca8a04",
      shadow: "0 24px 68px rgba(249, 115, 22, 0.10)",
      radius: "28px",
      backgroundArt: "radial-gradient(circle at top center, rgba(249,115,22,0.12), transparent 18%), linear-gradient(180deg, #fffef8 0%, #fff7e8 100%)",
    },
    nav: ["Courses", "Projects", "Faculty", "Bookings", "Community"],
    breadcrumbs: ["Kits", "Urban-adjacent", "Campus Wave"],
    tabs: ["Learning", "Operations", "Community"],
    toggles: ["Student", "Faculty", "Hybrid"],
    palette: [["Primary", "#f97316"], ["Accent", "#0f766e"], ["Success", "#16a34a"], ["Warning", "#ca8a04"], ["Surface", "#ffffff"]],
    metrics: [["Students", "62k", "+15%", "primary"], ["Assignments", "88%", "+7%", "success"], ["Spaces booked", "1,240", "+19%", "accent"], ["Support tickets", "34", "-11", "warning"]],
    bars: [["Courses", 81, "primary"], ["Projects", 69, "accent"], ["Events", 58, "success"], ["Support", 31, "warning"]],
    table: [["Course dashboard", "Published", "126 programs", "Learning"], ["Studio bookings", "Busy", "21 spaces", "Campus ops"], ["Mentor inbox", "Healthy", "87 threads", "Student success"], ["Faculty toolkit", "Expanding", "14 templates", "Academic ops"]],
    composition: [["Learning grid", "Layered", "Collaborative modules stay optimistic without becoming decorative."], ["Assignment form", "Practical", "Task entry and upload states are explicit and clean."], ["Community rail", "Active", "Campus events and academic tools coexist without crowding."]],
    commands: ["Inspect course modules", "Open assignment form", "Review booking sheet", "Jump to analytics table"],
    form: { titleLabel: "Program module", titlePlaceholder: "Collaborative studio booking", noteLabel: "Instructor update", notePlaceholder: "Write the key change and student action...", selectLabel: "Audience focus", selectOptions: ["Student", "Faculty", "Shared"], validationMessage: "Name the module clearly so students and staff can identify it at a glance." },
    alert: { title: "Studio slots released", body: "Students can book rooms for next week and the faculty toolkit reflects the new occupancy rules." },
    empty: { title: "No featured learning blocks", body: "Promote the course and collaboration modules you want the campus to notice first.", cta: "Feature module" },
  },
];
